### ISSUE TITLE
Doesn't work with MySQL 8 due to different default charset

### ISSUE THREAD

**Issue by jonaslm** [sensu-plugins/sensu-plugins-mysql#77]
MySQL 8 changed the default charset to utf8mb4. It seems this broke the mysql sensu scripts, as they all error out when connecting now.

```CheckMySQLHealth CRITICAL: MySQL check failed: unknown charset number: 255```

As far as I can tell, there's no configuration option for the scripts to tell what charset they should use when connecting.

**Comment by gonja-dude** [comment]
@jonaslm , had a similar issue when I upgraded mysql from 5 to 8 with latin1 as the charset. however, this problem later morphed into:
`CheckMysqlReplicationStatus CRITICAL: undefined method `encoding' for nil:NilClass`
Any idea on how to go approach this?

**Comment by jonaslm** [comment]
@gonja-dude 
No clue, sorry. We stopped using these checks since they didn't work for us anymore.

**Comment by gonja-dude** [comment]
@jonaslm 
Alright! Do you mind telling me what you guys are using now to check the replication status on your DBs?

**Comment by jonaslm** [comment]
We still haven't replaced them, sadly. If anyone finds a workable alternative we're also interested :)
